### ISSUE TITLE
debug screen after update.

### ISSUE THREAD

**Issue by masterofobzene** [HyperspaceMadness/Mega_Bezel#11]
HOW DO I TURN THIS OFF, BEFORE I DELETE THE WHOLE THING FOREVER?
![2024-03-23 18-34-14](https://github.com/HyperspaceMadness/Mega_Bezel/assets/94469116/0a6d3897-07d6-479f-b0f0-b20bca9e79fd)

**Comment by masterofobzene** [comment]
here is some feedback:

* has too many options that we dont know what are they for.
* has to be navigated using a controller because config files are a mess and nothing 
* can be changed using logic. e.x : 
`#pragma parameter HSM_MASK_DEBUG_EMPTY_LINE	" " 0 0 0.001 0.001`   <- (???)
* updating breaks the thing and you end up with a black screen with some info and can hear the game.

**Comment by HyperspaceMadness** [comment]
If you are loading a preset you have saved before, what is happening here is that you have saved a full preset rather than a simple preset, and then the Mega Bezel has been updated.

To successfully use your saved presets between Mega Bezel versions you'll need to use simple presets (which only have a reference to the base Mega Bezel preset originally loaded, and any parameter adjustments you have made) rather than full presets (which have a copy of all the passes inside)

You can learn more about simple presets here:

https://docs.libretro.com/guides/shaders/

Thanks for giving feedback, I'm doing the best I can within the existing framework.
